Invitation:
    type: entity
    table: invitation
    indexes:
        FK_Invit_Mess:
            columns:
                - idmessage
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idevenement:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    manyToOne:
        idmessage:
            targetEntity: Message
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idmessage:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
