Invitation:
    type: entity
    table: invitation
    id: {  }
    fields:
        idevenement:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    oneToOne:
        id:
            targetEntity: Message
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
