services:
    
    imie_network_site.admin.competence:
        class: ImieNetwork\SiteBundle\Admin\CompetenceAdmin
        arguments: [~, ImieNetwork\SiteBundle\Entity\Competence, ImieNetworkSiteBundle:CompetenceAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Tables fixes, label: Compétences}
            
    imie_network_site.admin.conversation:
        class: ImieNetwork\SiteBundle\Admin\ConversationAdmin
        arguments: [~, ImieNetwork\SiteBundle\Entity\Conversation, ImieNetworkSiteBundle:ConversationAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Administration, label: Conversations}
        
    imie_network_site.admin.document:
        class: ImieNetwork\SiteBundle\Admin\DocumentAdmin
        arguments: [~, ImieNetwork\SiteBundle\Entity\Document, ImieNetworkSiteBundle:DocumentAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Administration, label: Documents}
   
    imie_network_site.admin.evenement:
        class: ImieNetwork\SiteBundle\Admin\EvenementAdmin
        arguments: [~, ImieNetwork\SiteBundle\Entity\Evenement, ImieNetworkSiteBundle:EvenementAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Administration, label: Evènement}
 
    imie_network_site.admin.experience:
        class: ImieNetwork\SiteBundle\Admin\ExperienceAdmin
        arguments: [~, ImieNetwork\SiteBundle\Entity\Experience, ImieNetworkSiteBundle:ExperienceAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Administration, label: Expériences}
            
    imie_network_site.admin.groupe:
        class: ImieNetwork\SiteBundle\Admin\GroupeAdmin
        arguments: [~, ImieNetwork\SiteBundle\Entity\Groupe, ImieNetworkSiteBundle:GroupeAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Tables fixes, label: Groupe}
     
    imie_network_site.admin.module:
        class: ImieNetwork\SiteBundle\Admin\ModuleAdmin
        arguments: [~, ImieNetwork\SiteBundle\Entity\Module, ImieNetworkSiteBundle:ModuleAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Tables fixes, label: Modules}
            
    imie_network_site.admin.offre:
        class: ImieNetwork\SiteBundle\Admin\OffreAdmin
        arguments: [~, ImieNetwork\SiteBundle\Entity\Offre, ImieNetworkSiteBundle:OffreAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Administration, label: Offres}
            
    imie_network_site.admin.promotion:
        class: ImieNetwork\SiteBundle\Admin\PromotionAdmin
        arguments: [~, ImieNetwork\SiteBundle\Entity\Promotion, ImieNetworkSiteBundle:PromotionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Tables fixes, label: Promotions}
            
    imie_network_site.admin.proprieteetendue:
        class: ImieNetwork\SiteBundle\Admin\ProprieteetendueAdmin
        arguments: [~, ImieNetwork\SiteBundle\Entity\Proprieteetendue, ImieNetworkSiteBundle:ProprieteetendueAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Administration, label: Propriétés étendues}
          
    imie_network_site.admin.secteuractivite:
        class: ImieNetwork\SiteBundle\Admin\SecteuractiviteAdmin
        arguments: [~, ImieNetwork\SiteBundle\Entity\Secteuractivite, ImieNetworkSiteBundle:SecteuractiviteAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Tables fixes, label: Secteurs d'activités}
          
    imie_network_site.admin.typecontrat:
        class: ImieNetwork\SiteBundle\Admin\TypecontratAdmin
        arguments: [~, ImieNetwork\SiteBundle\Entity\Typecontrat, ImieNetworkSiteBundle:TypecontratAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Tables fixes, label: Types de contrats}

    imie_network_site.admin.typemessage:
        class: ImieNetwork\SiteBundle\Admin\TypemessageAdmin
        arguments: [~, ImieNetwork\SiteBundle\Entity\Typemessage, ImieNetworkSiteBundle:TypemessageAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Tables fixes, label: Types de messages}
    
    imie_network_site.admin.utilisateur:
        class: ImieNetwork\SiteBundle\Admin\UtilisateurAdmin
        arguments: [~, ImieNetwork\SiteBundle\Entity\Utilisateur, ImieNetworkSiteBundle:UtilisateurAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Administration, label: Utilisateurs}

    imie_network_site.admin.ville:
        class: ImieNetwork\SiteBundle\Admin\VilleAdmin
        arguments: [~, ImieNetwork\SiteBundle\Entity\Ville, ImieNetworkSiteBundle:VilleAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Tables fixes, label: Villes}
