imie_network_site_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ImieNetworkSiteBundle:Default:index }
testPage:
    pattern:  /test/{name}
    defaults: { _controller: ImieNetworkSiteBundle:Default:test }
eleveIndex:
    pattern:  /eleve
    defaults: { _controller: ImieNetworkSiteBundle:Eleve:index }
ImieNetworkSiteBundle_utilisateur:
    resource: "@ImieNetworkSiteBundle/Resources/config/routing/utilisateur.yml"
    prefix:   /utilisateur
ImieNetworkSiteBundle_evenement:
        resource: "@ImieNetworkSiteBundle/Resources/config/routing/evenement.yml"
        prefix:   /evenement
        
ImieNetworkSiteBundle_administration:
        resource: "@ImieNetworkSiteBundle/Resources/config/routing/administration.yml"
        prefix:   /administration

