imie_network_site_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ImieNetworkSiteBundle:Default:index }
testPage:
    pattern:  /test/{name}
    defaults: { _controller: ImieNetworkSiteBundle:Default:test }
eleveIndex:
    pattern:  /eleve
    defaults: { _controller: ImieNetworkSiteBundle:Eleve:index }
administrationIndex:
    pattern:  /administration
    defaults: { _controller: ImieNetworkSiteBundle:Administration:index }
entrepriseIndex:
    pattern:  /entreprise
    defaults: { _controller: ImieNetworkSiteBundle:Entreprise:index }
