imie_network_site_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ImieNetworkSiteBundle:Default:index }
testPage:
    pattern:  /test/{name}
    defaults: { _controller: ImieNetworkSiteBundle:Default:test }
entrepriseIndex:
    pattern:  /entreprise/{name}
    defaults: { _controller: ImieNetworkSiteBundle:Entreprise:index }
eleveIndex:
    pattern:  /eleve/{name}
    defaults: { _controller: ImieNetworkSiteBundle:Eleve:index }
    
ImieNetworkSiteBundle_utilisateur:
    resource: "@ImieNetworkSiteBundle/Resources/config/routing/utilisateur.yml"
    prefix:   /utilisateur

ImieNetworkSiteBundle_evenement:
        resource: "@ImieNetworkSiteBundle/Resources/config/routing/evenement.yml"
        prefix:   /evenement
        
ImieNetworkSiteBundle_administration:
        resource: "@ImieNetworkSiteBundle/Resources/config/routing/administration.yml"
        prefix:   /administration