imie_network_site_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ImieNetworkSiteBundle:Default:index }
testPage:
    pattern:  /test/{name}
    defaults: { _controller: ImieNetworkSiteBundle:Default:test }
ImieNetworkSiteBundle_evenement:
    resource: "@ImieNetworkSiteBundle/Resources/config/routing/evenement.yml"
    prefix:   /evenement  
ImieNetworkSiteBundle_administration:
    resource: "@ImieNetworkSiteBundle/Resources/config/routing/administration.yml"
    prefix:   /administration
ImieNetworkSiteBundle_eleve:
    resource: "@ImieNetworkSiteBundle/Resources/config/routing/eleve.yml"
    prefix:   /eleve
ImieNetworkSiteBundle_entreprise:
    resource: "@ImieNetworkSiteBundle/Resources/config/routing/entreprise.yml"
    prefix:   /entreprise
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    