imie_network_site_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ImieNetworkSiteBundle:Default:index }
testPage:
    pattern:  /test/{name}
    defaults: { _controller: ImieNetworkSiteBundle:Default:test }
entrepriseIndex:
    pattern:  /entreprise/{name}
    defaults: { _controller: ImieNetworkSiteBundle:Entreprise:index }
eleveIndex:
    pattern:  /eleve/{name}
    defaults: { _controller: ImieNetworkSiteBundle:Eleve:index }
administrationIndex:
    pattern:  /administration/{name}
    defaults: { _controller: ImieNetworkSiteBundle:Administration:index }