imie_network_site:
    resource: "@ImieNetworkSiteBundle/Resources/config/routing.yml"
    prefix:   /
    
imie_network_api:
    type: rest
    resource: "@ImieNetworkSiteBundle/Resources/config/routing_rest.yml"
    prefix: /api
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc

