ImieNetwork\SiteBundle\Entity\Conversationutilisateur:
    type: entity
    repositoryClass: ImieNetwork\SiteBundle\Entity\ConversationutilisateurRepository
    table: conversationutilisateur
    indexes:
        FK_ConvUt_Conv:
            columns:
                - idconversation
        FK_ConvUt_Util:
            columns:
                - idutilisateur
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        idconversation:
            targetEntity: Conversation
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idconversation:
                    referencedColumnName: id
            orphanRemoval: false
        idutilisateur:
            targetEntity: Utilisateur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idutilisateur:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
