ImieNetwork\SiteBundle\Entity\Conversation:
    type: entity
    table: conversation
    indexes:
        FK_Conv_Util:
            columns:
                - idutilisateur
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        contenu:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        dateconv:
            type: datetime
            nullable: true
            comment: ''
    manyToOne:
        idutilisateur:
            targetEntity: Utilisateur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idutilisateur:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
