ImieNetwork\SiteBundle\Entity\Enquete:
    type: entity
    repositoryClass: ImieNetwork\SiteBundle\Repository\EnqueteRepository
    table: enquete
    indexes:
        FK_Enq_Mess:
            columns:
                - idmessage
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        url:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
    manyToOne:
        idmessage:
            targetEntity: Message
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idmessage:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
