ImieNetwork\SiteBundle\Entity\Evenementutilisateur:
    type: entity
    repositoryClass: ImieNetwork\SiteBundle\Entity\EvenementutilisateurRepository
    table: evenementutilisateur
    indexes:
        FK_Part_Util:
            columns:
                - idutilisateur
        FK_Part_Evnt:
            columns:
                - idevenement
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        participe:
            type: boolean
            nullable: true
            comment: ''
    manyToOne:
        idutilisateur:
            targetEntity: Utilisateur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idutilisateur:
                    referencedColumnName: id
            orphanRemoval: false
        idevenement:
            targetEntity: Evenement
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idevenement:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
