ImieNetwork\SiteBundle\Entity\Groupeutilisateur:
    type: entity
    repositoryClass: ImieNetwork\SiteBundle\Entity\GroupeutilisateurRepository
    table: groupeutilisateur
    indexes:
        FK_GpUser_Util:
            columns:
                - idutilisateur
        FK_GpUser_Gp:
            columns:
                - idgroupe
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        idutilisateur:
            targetEntity: Utilisateur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idutilisateur:
                    referencedColumnName: id
            orphanRemoval: false
        idgroupe:
            targetEntity: Groupe
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idgroupe:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
