ImieNetwork\SiteBundle\Entity\Offreville:
    type: entity
    repositoryClass: ImieNetwork\SiteBundle\Entity\OffrevilleRepository
    table: offreville
    indexes:
        FK_OffVill_Off:
            columns:
                - idoffre
        FK_OffDept_Dept:
            columns:
                - idville
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        idoffre:
            targetEntity: Offre
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idoffre:
                    referencedColumnName: id
            orphanRemoval: false
        idville:
            targetEntity: Ville
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idville:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
