ImieNetwork\SiteBundle\Entity\Offre:
    type: entity
    repositoryClass: ImieNetwork\SiteBundle\Repository\OffreRepository
    table: offre
    indexes:
        FK_Offre_TypeCt:
            columns:
                - idtypecontrat
        FK_Offre_Util:
            columns:
                - idutilisateur
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        detailcontact:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        duree:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        typeposte:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        datedebut:
            type: datetime
            nullable: true
            comment: ''
        datemodification:
            type: datetime
            nullable: true
            comment: ''
        datefinpublication:
            type: datetime
            nullable: true
            comment: ''
        datefin:
            type: datetime
            nullable: true
            comment: ''
    manyToOne:
        idtypecontrat:
            targetEntity: Typecontrat
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idtypecontrat:
                    referencedColumnName: id
            orphanRemoval: false
        idutilisateur:
            targetEntity: Utilisateur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idutilisateur:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
