ImieNetwork\SiteBundle\Entity\Utilisateurcompetence:
    type: entity
    repositoryClass: ImieNetwork\SiteBundle\Entity\UtilisateurcompetenceRepository
    table: utilisateurcompetence
    indexes:
        FK_UtCp_Gp:
            columns:
                - idutilisateur
        FK_UtCp_CP:
            columns:
                - idcompetence
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        note:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
    manyToOne:
        idutilisateur:
            targetEntity: Utilisateur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idutilisateur:
                    referencedColumnName: id
            orphanRemoval: false
        idcompetence:
            targetEntity: Competence
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcompetence:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
