ImieNetwork\SiteBundle\Entity\Utilisateur:
    type: entity
    table: utilisateur
    indexes:
        FK_Part_Vill:
            columns:
                - idville
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        adresse:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        telephone:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        statut:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        login:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        pass:
            type: string
            nullable: true
            length: 15
            fixed: false
            comment: ''
        email:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        datecreation:
            type: datetime
            nullable: true
            comment: ''
        datemodification:
            type: datetime
            nullable: true
            comment: ''
        langue:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
    manyToOne:
        idville:
            targetEntity: Ville
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idville:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
