ImieNetwork\SiteBundle\Entity\Utilisateurpromotion:
    type: entity
    repositoryClass: ImieNetwork\SiteBundle\Repository\UtilisateurpromotionRepository
    table: utilisateurpromotion
    indexes:
        FK_utilPromo_Util:
            columns:
                - idutilisateur
        FK_ElvPromo_Promo:
            columns:
                - idpromotion
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        idutilisateur:
            targetEntity: Utilisateur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idutilisateur:
                    referencedColumnName: id
            orphanRemoval: false
        idpromotion:
            targetEntity: Promotion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idpromotion:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
