administrationIndex:
    pattern:  /
    defaults: { _controller: ImieNetworkSiteBundle:Administration:index }

administrationutilisateurIndex:
    pattern:  /utilisateur/
    defaults: { _controller: ImieNetworkSiteBundle:Administration:indexUtilisateur }

admnistrationutilisateurnew:
    pattern: /utilisateur/new
    defaults: { _controller: ImieNetworkSiteBundle:Administration:newUtilisateur }

administrationutilisateuredit:
    pattern: /utilisateur/{id}/edit
    defaults: { _controller: ImieNetworkSiteBundle:Administration:editUtilisateur }
    
administrationutilisateurshow:
    pattern: /utilisateur/{id}/show
    defaults: { _controller: ImieNetworkSiteBundle:Administration:showUtilisateur }

administrationutilisateurdelete:
    pattern: /utilisateur/{id}/delete
    defaults: { _controller: ImieNetworkSiteBundle:Administration:deleteUtilisateur }
    requirements: { _method: post|delete }
    
administrationutilisateurupdate:
    pattern: /utilisateur/{id}/update
    defaults: { _controller: ImieNetworkSiteBundle:Administration:updateUtilisateur }
    requirements: { _method: post|put }
    
administrationutilisateurcreate:
    pattern: /utilisateur/create
    defaults: { _controller: ImieNetworkSiteBundle:Administration:createUtilisateur }
    requirements: { _method: post }