administrationutilisateurIndex:
    pattern:  /utilisateur/
    defaults: { _controller: ImieNetworkSiteBundle:Administration:indexUtilisateur }

admnistrationutilisateurnew:
    pattern: /utilisateur/new
    defaults: { _controller: ImieNetworkSiteBundle:Administration:newUtilisateur }

administrationutilisateuredit:
    pattern: /utilisateur/{id}/edit
    defaults: { _controller: ImieNetworkSiteBundle:Administration:editUtilisateur }

administrationutilisateurdelete:
    pattern: /utilisateur/{id}/delete
    defaults: { _controller: ImieNetworkSiteBundle:Administration:deleteUtilisateur }