entrepriseIndex:
    pattern:  /
    defaults: { _controller: ImieNetworkSiteBundle:Entreprise:index }
entrepriselistMesOffres:
    pattern: /list-mes-offres
    defaults: { _controller: ImieNetworkSiteBundle:Entreprise:mesOffres }