offre:
    pattern:  /
    defaults: { _controller: "ImieNetworkSiteBundle:Offre:index" }

offre_show:
    pattern:  /show/{id}
    defaults: { _controller: "ImieNetworkSiteBundle:Offre:show" }

offre_new:
    pattern:  /new
    defaults: { _controller: "ImieNetworkSiteBundle:Offre:new" }

offre_create:
    pattern:  /create
    defaults: { _controller: "ImieNetworkSiteBundle:Offre:create" }
    requirements: { _method: post }

offre_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "ImieNetworkSiteBundle:Offre:edit" }

offre_update:
    pattern:  /update/{id}
    defaults: { _controller: "ImieNetworkSiteBundle:Offre:update" }
    requirements: { _method: post|put }

offre_delete:
    pattern:  /delete/{id}
    defaults: { _controller: "ImieNetworkSiteBundle:Offre:delete" }
    requirements: { _method: post|delete }
    
offre_search:
    pattern:  /search
    defaults: { _controller: "ImieNetworkSiteBundle:Offre:search" }

offre_showsearch:
    pattern:    /show
    defaults:   { _controller: "ImieNetworkSiteBundle:Offre:showsearch" }

offre_showsearch_all:
    pattern:    /showall
    defaults:   { _controller: "ImieNetworkSiteBundle:Offre:showsearchall" }