entrepriselistMesOffres:
    pattern: /
    defaults: { _controller: ImieNetworkSiteBundle:Entreprise/Offre:index }
entrepriseshowOffre:
    pattern: /detail/{id}
    defaults: { _controller: ImieNetworkSiteBundle:Entreprise/Offre:show }